[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dark_pool_program = "4kK1X4Dnxomgn858uCGvkfRtZhYd71r439hhz1ueNpF6"

[programs.devnet]
dark_pool_program = "4kK1X4Dnxomgn858uCGvkfRtZhYd71r439hhz1ueNpF6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
